import { DEFAULT_ANCHORS, type Species } from "../types";

/** Tier "difficile" — mythical creatures: 20 species (9 / 6 / 4 / 1). */
export const DIFFICILE_SPECIES: Species[] = [
  {
    id: "difficile-dragonnet",
    tier: "difficile",
    rarity: "commun",
    name: "Braise",
    tagline: "Éternue des étincelles quand il est content.",
    palette: { primary: "#D9666B", secondary: "#7A2E32", accent: "#F0D68F", eye: "#F7E7CE" },
    parts: { body: "round", ears: "horns", eyes: "sharp", mouth: "fangs", tail: "thin", markings: "scales", extra: null },
    anchors: DEFAULT_ANCHORS.round,
    signature: "bandana",
  },
  {
    id: "difficile-feu-follet",
    tier: "difficile",
    rarity: "commun",
    name: "Lumi",
    tagline: "Une petite lumière qui danse dans la nuit.",
    palette: { primary: "#7DD9C9", secondary: "#3F8F84", accent: "#F7F4EC", eye: "#1F3A36" },
    parts: { body: "blob", ears: "none", eyes: "sparkle", mouth: "small", tail: "none", markings: "none", extra: null },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "star_pin",
  },
  {
    id: "difficile-gargouille",
    tier: "difficile",
    rarity: "commun",
    name: "Pierrot",
    tagline: "Veille sur les toits, mais préfère les cuisines.",
    palette: { primary: "#8A8F96", secondary: "#4E535A", accent: "#B8BEC6", eye: "#F0D68F" },
    parts: { body: "tall", ears: "horns", eyes: "sharp", mouth: "fangs", tail: "thin", markings: "stripes", extra: null },
    anchors: DEFAULT_ANCHORS.tall,
    signature: "monocle",
  },
  {
    id: "difficile-salamandre",
    tier: "difficile",
    rarity: "commun",
    name: "Ambrine",
    tagline: "Aime la chaleur des fourneaux.",
    palette: { primary: "#E8853A", secondary: "#9C4A1E", accent: "#F0D68F", eye: "#2B2B2B" },
    parts: { body: "serpent", ears: "none", eyes: "sleepy", mouth: "smile", tail: "thin", markings: "spots", extra: null },
    anchors: DEFAULT_ANCHORS.serpent,
    signature: "leaf",
  },
  {
    id: "difficile-sylphe",
    tier: "difficile",
    rarity: "commun",
    name: "Zéphyrine",
    tagline: "Légère comme une brise de printemps.",
    palette: { primary: "#C7D8F2", secondary: "#8EA8D6", accent: "#F7F4EC", eye: "#3A4A66" },
    parts: { body: "egg", ears: "none", eyes: "sparkle", mouth: "smile", tail: "feather", markings: "crescent", extra: null },
    anchors: DEFAULT_ANCHORS.egg,
    signature: "flower",
  },
  {
    id: "difficile-golem",
    tier: "difficile",
    rarity: "rare",
    name: "Rocaille",
    tagline: "Solide comme un roc, doux comme la mousse.",
    palette: { primary: "#A08A6E", secondary: "#5E4630", accent: "#7FB77E", eye: "#F0D68F" },
    parts: { body: "blob", ears: "none", eyes: "sleepy", mouth: "small", tail: "none", markings: "shell", extra: null },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "leaf",
  },
  {
    id: "difficile-kitsune",
    tier: "difficile",
    rarity: "rare",
    name: "Kitsu",
    tagline: "Neuf queues dit-on, mais elle n'en montre qu'une.",
    palette: { primary: "#F7F4EC", secondary: "#D9666B", accent: "#E8C36A", eye: "#2B2B2B" },
    parts: { body: "round", ears: "fox", eyes: "sharp", mouth: "smile", tail: "fluffy", markings: "mask", extra: null },
    anchors: DEFAULT_ANCHORS.round,
    signature: "bell",
  },
  {
    id: "difficile-licorne",
    tier: "difficile",
    rarity: "rare",
    name: "Opaline",
    tagline: "Ne mange que ce qui a poussé au soleil.",
    palette: { primary: "#F2DDE8", secondary: "#B48AE0", accent: "#E8C36A", eye: "#5B3A6B" },
    parts: { body: "tall", ears: "horn", eyes: "sparkle", mouth: "smile", tail: "fluffy", markings: "none", extra: null },
    anchors: DEFAULT_ANCHORS.tall,
    signature: "pearl",
  },
  {
    id: "difficile-phenix",
    tier: "difficile",
    rarity: "tres_rare",
    name: "Solaris",
    tagline: "Renaît de ses cendres, et de tes bons repas.",
    palette: { primary: "#E8853A", secondary: "#D9666B", accent: "#F0D68F", eye: "#F7F4EC" },
    parts: { body: "egg", ears: "none", eyes: "sharp", mouth: "beak", tail: "feather", markings: "none", extra: ["wings", "flames"] },
    anchors: DEFAULT_ANCHORS.egg,
    signature: "star_pin",
  },
  {
    id: "difficile-dragon-celeste",
    tier: "difficile",
    rarity: "legendaire",
    name: "Azurion",
    tagline: "Le dragon des cieux protège ceux qui prennent soin d'eux.",
    palette: { primary: "#4A6FD6", secondary: "#2A3F8C", accent: "#F0D68F", eye: "#F0D68F" },
    parts: { body: "round", ears: "horns", eyes: "sparkle", mouth: "fangs", tail: "curl", markings: "scales", extra: ["wings", "halo", "crystals"] },
    anchors: DEFAULT_ANCHORS.round,
    signature: "crown",
  },
  // ---- phase 5 additions ----
  {
    id: "difficile-lutin-farceur",
    tier: "difficile",
    rarity: "commun",
    name: "Filou",
    tagline: "Cache les chaussettes et rend les cuillères.",
    palette: { primary: "#7FB77E", secondary: "#3F6B3E", accent: "#F0D68F", eye: "#2B2B2B" },
    parts: { body: "tall", ears: "cat", eyes: "sharp", mouth: "smile", tail: "thin", markings: "none", extra: null },
    anchors: DEFAULT_ANCHORS.tall,
    signature: "bell",
  },
  {
    id: "difficile-slime-gourmand",
    tier: "difficile",
    rarity: "commun",
    name: "Gluglu",
    tagline: "Absorbe tout ce qui traîne, préfère les fruits.",
    palette: { primary: "#8FD6B8", secondary: "#4FA88F", accent: "#F7F4EC", eye: "#1F3A36" },
    parts: { body: "blob", ears: "none", eyes: "big", mouth: "smile", tail: "none", markings: "spots", extra: null },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "star_pin",
  },
  {
    id: "difficile-chauve-souris",
    tier: "difficile",
    rarity: "commun",
    name: "Nocta",
    tagline: "Se réveille au dîner, adore les mangues.",
    palette: { primary: "#5F4B9C", secondary: "#3A2F6B", accent: "#F0A9B0", eye: "#F0D68F" },
    parts: { body: "round", ears: "fox", eyes: "sharp", mouth: "fangs", tail: "none", markings: "belly_patch", extra: null },
    anchors: DEFAULT_ANCHORS.round,
    signature: "bandana",
  },
  {
    id: "difficile-champignon-sage",
    tier: "difficile",
    rarity: "commun",
    name: "Mycos",
    tagline: "Pousse après la pluie, philosophe avant le repas.",
    palette: { primary: "#F2E8D8", secondary: "#D9666B", accent: "#F7F4EC", eye: "#2B2B2B" },
    parts: { body: "blob", ears: "none", eyes: "sleepy", mouth: "small", tail: "none", markings: "mask", extra: null },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "leaf",
  },
  {
    id: "difficile-griffon-fier",
    tier: "difficile",
    rarity: "rare",
    name: "Griffus",
    tagline: "Mi-aigle mi-lion, entièrement gourmand.",
    palette: { primary: "#D9A066", secondary: "#8C5A3A", accent: "#F0D68F", eye: "#2B2B2B" },
    parts: { body: "tall", ears: "cat", eyes: "sharp", mouth: "beak", tail: "fluffy", markings: "mask", extra: null },
    anchors: DEFAULT_ANCHORS.tall,
    signature: "crown",
  },
  {
    id: "difficile-yeti-timide",
    tier: "difficile",
    rarity: "rare",
    name: "Yétou",
    tagline: "Un géant timide qui adore les soupes chaudes.",
    palette: { primary: "#F7F4EC", secondary: "#C7D8F2", accent: "#7DA7D9", eye: "#2B2B2B" },
    parts: { body: "blob", ears: "round", eyes: "sleepy", mouth: "smile", tail: "none", markings: "belly_patch", extra: null },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "scarf",
  },
  {
    id: "difficile-ondine-rieuse",
    tier: "difficile",
    rarity: "rare",
    name: "Ondine",
    tagline: "Chante sous la pluie et rit sous le soleil.",
    palette: { primary: "#5FB8C9", secondary: "#2F6E7A", accent: "#F0D68F", eye: "#2B2B2B" },
    parts: { body: "serpent", ears: "none", eyes: "sparkle", mouth: "smile", tail: "feather", markings: "scales", extra: null },
    anchors: DEFAULT_ANCHORS.serpent,
    signature: "pearl",
  },
  {
    id: "difficile-phenix-de-glace",
    tier: "difficile",
    rarity: "tres_rare",
    name: "Givréa",
    tagline: "Ses flammes sont froides, son cœur brûlant.",
    palette: { primary: "#C7E6F2", secondary: "#7DA7D9", accent: "#F7F4EC", eye: "#2B4A66" },
    parts: { body: "egg", ears: "none", eyes: "sharp", mouth: "beak", tail: "feather", markings: "none", extra: ["wings", "aura"] },
    anchors: DEFAULT_ANCHORS.egg,
    signature: "star_pin",
  },
  {
    id: "difficile-dragon-de-jade",
    tier: "difficile",
    rarity: "tres_rare",
    name: "Jadéon",
    tagline: "Long comme une rivière, sage comme une montagne.",
    palette: { primary: "#5FA88F", secondary: "#2F5E4E", accent: "#F0D68F", eye: "#F0D68F" },
    parts: { body: "serpent", ears: "horns", eyes: "sharp", mouth: "fangs", tail: "thin", markings: "scales", extra: ["crystals", "aura"] },
    anchors: DEFAULT_ANCHORS.serpent,
    signature: "crown",
  },
  {
    id: "difficile-esprit-celeste",
    tier: "difficile",
    rarity: "tres_rare",
    name: "Astrëa",
    tagline: "Un morceau de ciel nocturne descendu te tenir compagnie.",
    palette: { primary: "#2E3A6B", secondary: "#8E9BC7", accent: "#F0D68F", eye: "#F7F4EC" },
    parts: { body: "blob", ears: "none", eyes: "sparkle", mouth: "smile", tail: "none", markings: "crescent", extra: ["halo", "aura"] },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "star_pin",
  },
];
