import { DEFAULT_ANCHORS, type Species } from "../types";

/**
 * Tier "facile" — cosy domestic companions: 20 species
 * (9 commun, 6 rare, 4 très rare, 1 légendaire).
 */
export const FACILE_SPECIES: Species[] = [
  {
    id: "facile-chat-rond",
    tier: "facile",
    rarity: "commun",
    name: "Chabond",
    tagline: "Ronronne quand on lui sert du poisson.",
    palette: { primary: "#8BA07A", secondary: "#5E7053", accent: "#E8C36A", eye: "#2B2B2B" },
    parts: { body: "round", ears: "cat", eyes: "big", mouth: "smile", tail: "curl", markings: "belly_patch", extra: null },
    anchors: DEFAULT_ANCHORS.round,
    signature: "bow",
  },
  {
    id: "facile-lapin-doux",
    tier: "facile",
    rarity: "commun",
    name: "Lapinou",
    tagline: "Grignote tout ce qui est vert, surtout les carottes.",
    palette: { primary: "#DDD3C4", secondary: "#B9A995", accent: "#F0A9B0", eye: "#3A2E2E" },
    parts: { body: "egg", ears: "rabbit", eyes: "sparkle", mouth: "small", tail: "puff", markings: "none", extra: null },
    anchors: DEFAULT_ANCHORS.egg,
    signature: "flower",
  },
  {
    id: "facile-hamster-joufflu",
    tier: "facile",
    rarity: "commun",
    name: "Hamsto",
    tagline: "Stocke ses graines dans ses joues pour plus tard.",
    palette: { primary: "#E0A96D", secondary: "#B8834B", accent: "#F7E7CE", eye: "#2B2B2B" },
    parts: { body: "blob", ears: "round", eyes: "big", mouth: "smile", tail: "none", markings: "spots", extra: null },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "star_pin",
  },
  {
    id: "facile-canard-dodu",
    tier: "facile",
    rarity: "commun",
    name: "Coincoin",
    tagline: "Aime l'eau, les flaques et les longues balades.",
    palette: { primary: "#F2D16B", secondary: "#D4B24C", accent: "#E8853A", eye: "#2B2B2B" },
    parts: { body: "egg", ears: "none", eyes: "big", mouth: "beak", tail: "feather", markings: "none", extra: null },
    anchors: DEFAULT_ANCHORS.egg,
    signature: "leaf",
  },
  {
    id: "facile-corgi-fute",
    tier: "facile",
    rarity: "commun",
    name: "Toutou",
    tagline: "Suit ses humains partout, surtout à l'heure du goûter.",
    palette: { primary: "#D98F52", secondary: "#F2E8D8", accent: "#E39B4A", eye: "#2B2B2B" },
    parts: { body: "tall", ears: "fold", eyes: "big", mouth: "tongue", tail: "stub", markings: "mask", extra: null },
    anchors: DEFAULT_ANCHORS.tall,
    signature: "bandana",
  },
  {
    id: "facile-herisson-timide",
    tier: "facile",
    rarity: "rare",
    name: "Piquou",
    tagline: "Se roule en boule dès qu'il entend un bruit.",
    palette: { primary: "#C9A27A", secondary: "#5E4630", accent: "#F0C9A0", eye: "#2B2B2B" },
    parts: { body: "round", ears: "round", eyes: "sleepy", mouth: "small", tail: "none", markings: "spikes", extra: null },
    anchors: DEFAULT_ANCHORS.round,
    signature: "leaf",
  },
  {
    id: "facile-cochon-rose",
    tier: "facile",
    rarity: "rare",
    name: "Groin",
    tagline: "Un gourmet : il sait reconnaître un bon légume.",
    palette: { primary: "#F2B8C6", secondary: "#D98FA3", accent: "#E38EA5", eye: "#2B2B2B" },
    parts: { body: "round", ears: "pig", eyes: "big", mouth: "snout", tail: "thin", markings: "spots", extra: null },
    anchors: DEFAULT_ANCHORS.round,
    signature: "bell",
  },
  {
    id: "facile-tortue-sage",
    tier: "facile",
    rarity: "rare",
    name: "Tortuline",
    tagline: "Prend son temps, mais n'oublie jamais un repas.",
    palette: { primary: "#8FBF8F", secondary: "#5E7053", accent: "#C9A24E", eye: "#2B2B2B" },
    parts: { body: "blob", ears: "none", eyes: "sleepy", mouth: "smile", tail: "thin", markings: "shell", extra: null },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "monocle",
  },
  {
    id: "facile-lapin-lune",
    tier: "facile",
    rarity: "tres_rare",
    name: "Lunou",
    tagline: "N'apparaît que les soirs de pleine lune.",
    palette: { primary: "#C7CFE6", secondary: "#8E9BC7", accent: "#F0D68F", eye: "#2B2B4B" },
    parts: { body: "egg", ears: "rabbit", eyes: "sparkle", mouth: "small", tail: "puff", markings: "crescent", extra: "aura" },
    anchors: DEFAULT_ANCHORS.egg,
    signature: "star_pin",
  },
  {
    id: "facile-chat-aurore",
    tier: "facile",
    rarity: "legendaire",
    name: "Aurorin",
    tagline: "On dit qu'il porte chance à ceux qui mangent équilibré.",
    palette: { primary: "#E8C36A", secondary: "#C9A24E", accent: "#FFF3C4", eye: "#5B3A1E" },
    parts: { body: "round", ears: "cat", eyes: "sparkle", mouth: "smile", tail: "fluffy", markings: "stripes", extra: ["wings", "halo"] },
    anchors: DEFAULT_ANCHORS.round,
    signature: "crown",
  },
  // ---- phase 5 additions ----
  {
    id: "facile-poussin-pipelette",
    tier: "facile",
    rarity: "commun",
    name: "Pioupiou",
    tagline: "Piaille de joie dès qu'il voit des graines.",
    palette: { primary: "#F7E27A", secondary: "#E0B94C", accent: "#E8853A", eye: "#2B2B2B" },
    parts: { body: "egg", ears: "none", eyes: "big", mouth: "beak", tail: "feather", markings: "none", extra: null },
    anchors: DEFAULT_ANCHORS.egg,
    signature: "flower",
  },
  {
    id: "facile-souris-curieuse",
    tier: "facile",
    rarity: "commun",
    name: "Grignote",
    tagline: "Fouine partout, surtout dans le placard.",
    palette: { primary: "#B8B4C2", secondary: "#8C879A", accent: "#F0A9B0", eye: "#2B2B2B" },
    parts: { body: "round", ears: "round", eyes: "big", mouth: "small", tail: "thin", markings: "belly_patch", extra: null },
    anchors: DEFAULT_ANCHORS.round,
    signature: "pearl",
  },
  {
    id: "facile-chiot-beagle",
    tier: "facile",
    rarity: "commun",
    name: "Bagel",
    tagline: "Renifle chaque assiette avec le plus grand sérieux.",
    palette: { primary: "#F2E8D8", secondary: "#8C5A3A", accent: "#2B2B2B", eye: "#2B2B2B" },
    parts: { body: "tall", ears: "fold", eyes: "big", mouth: "tongue", tail: "stub", markings: "spots", extra: null },
    anchors: DEFAULT_ANCHORS.tall,
    signature: "bandana",
  },
  {
    id: "facile-cochon-dinde",
    tier: "facile",
    rarity: "commun",
    name: "Pipo",
    tagline: "Couine de bonheur devant une feuille de salade.",
    palette: { primary: "#D9A066", secondary: "#F7F4EC", accent: "#F0C9A0", eye: "#2B2B2B" },
    parts: { body: "blob", ears: "round", eyes: "big", mouth: "small", tail: "none", markings: "spots", extra: null },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "leaf",
  },
  {
    id: "facile-panda-roux",
    tier: "facile",
    rarity: "rare",
    name: "Roupanda",
    tagline: "Fait la sieste dans les arbres, mange des pousses.",
    palette: { primary: "#C0623A", secondary: "#F2E8D8", accent: "#2B2B2B", eye: "#2B2B2B" },
    parts: { body: "round", ears: "round", eyes: "big", mouth: "smile", tail: "fluffy", markings: "mask", extra: null },
    anchors: DEFAULT_ANCHORS.round,
    signature: "scarf",
  },
  {
    id: "facile-chat-siamois",
    tier: "facile",
    rarity: "rare",
    name: "Siamoune",
    tagline: "Élégante, bavarde, et un peu snob avec les croquettes.",
    palette: { primary: "#EAD9C4", secondary: "#5E4630", accent: "#7DA7D9", eye: "#4A6FA5" },
    parts: { body: "tall", ears: "cat", eyes: "sharp", mouth: "small", tail: "thin", markings: "badger", extra: null },
    anchors: DEFAULT_ANCHORS.tall,
    signature: "pearl",
  },
  {
    id: "facile-loutre-joueuse",
    tier: "facile",
    rarity: "rare",
    name: "Loutrine",
    tagline: "Dort sur le dos et tient ta main dans son sommeil.",
    palette: { primary: "#8C6A4A", secondary: "#5E4630", accent: "#E8D3B8", eye: "#2B2B2B" },
    parts: { body: "tall", ears: "round", eyes: "sleepy", mouth: "smile", tail: "thin", markings: "belly_patch", extra: null },
    anchors: DEFAULT_ANCHORS.tall,
    signature: "bell",
  },
  {
    id: "facile-chat-nuage",
    tier: "facile",
    rarity: "tres_rare",
    name: "Nimbus",
    tagline: "Aussi léger qu'un nuage, aussi doux qu'une sieste.",
    palette: { primary: "#F7F4EC", secondary: "#C7D8F2", accent: "#7DA7D9", eye: "#4A6FA5" },
    parts: { body: "blob", ears: "cat", eyes: "sparkle", mouth: "smile", tail: "puff", markings: "none", extra: "aura" },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "star_pin",
  },
  {
    id: "facile-lapin-cristal",
    tier: "facile",
    rarity: "tres_rare",
    name: "Cristaline",
    tagline: "Ses oreilles tintent quand elle est contente.",
    palette: { primary: "#F2DDE8", secondary: "#C58FD6", accent: "#F7F4EC", eye: "#6B3A7A" },
    parts: { body: "egg", ears: "rabbit", eyes: "sparkle", mouth: "small", tail: "puff", markings: "spots", extra: "crystals" },
    anchors: DEFAULT_ANCHORS.egg,
    signature: "crown",
  },
  {
    id: "facile-canard-iris",
    tier: "facile",
    rarity: "tres_rare",
    name: "Iris",
    tagline: "Ses plumes changent de couleur avec la lumière.",
    palette: { primary: "#9FD6C8", secondary: "#5FA88F", accent: "#E38EA5", eye: "#2B2B2B" },
    parts: { body: "egg", ears: "none", eyes: "sparkle", mouth: "beak", tail: "feather", markings: "spots", extra: "aura" },
    anchors: DEFAULT_ANCHORS.egg,
    signature: "flower",
  },
];
