import { DEFAULT_ANCHORS, type Species } from "../types";

/** Tier "moyen" — forest creatures. Phase 3 ships the first 10 of 20. */
export const MOYEN_SPECIES: Species[] = [
  {
    id: "moyen-renard-malin",
    tier: "moyen",
    rarity: "commun",
    name: "Roussette",
    tagline: "Rusée, mais jamais avec ses amis.",
    palette: { primary: "#D97A3A", secondary: "#F2E8D8", accent: "#F7E7CE", eye: "#2B2B2B" },
    parts: { body: "round", ears: "fox", eyes: "sharp", mouth: "smile", tail: "fluffy", markings: "belly_patch", extra: null },
    anchors: DEFAULT_ANCHORS.round,
    signature: "scarf",
  },
  {
    id: "moyen-hibou-savant",
    tier: "moyen",
    rarity: "commun",
    name: "Houhou",
    tagline: "Veille tard et sait beaucoup de choses.",
    palette: { primary: "#8C7358", secondary: "#5A4632", accent: "#E8C36A", eye: "#2B2B2B" },
    parts: { body: "egg", ears: "cat", eyes: "big", mouth: "beak", tail: "feather", markings: "belly_patch", extra: null },
    anchors: DEFAULT_ANCHORS.egg,
    signature: "monocle",
  },
  {
    id: "moyen-ecureuil-vif",
    tier: "moyen",
    rarity: "commun",
    name: "Noisette",
    tagline: "Ne tient pas en place, surtout à l'automne.",
    palette: { primary: "#B5652E", secondary: "#F2E8D8", accent: "#F7E7CE", eye: "#2B2B2B" },
    parts: { body: "round", ears: "round", eyes: "big", mouth: "small", tail: "fluffy", markings: "belly_patch", extra: null },
    anchors: DEFAULT_ANCHORS.round,
    signature: "leaf",
  },
  {
    id: "moyen-blaireau-calme",
    tier: "moyen",
    rarity: "commun",
    name: "Grisou",
    tagline: "Ne se presse jamais, et ça lui réussit.",
    palette: { primary: "#B9BFB8", secondary: "#2B2B2B", accent: "#F2EFE6", eye: "#2B2B2B" },
    parts: { body: "blob", ears: "round", eyes: "sleepy", mouth: "small", tail: "stub", markings: "badger", extra: null },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "bandana",
  },
  {
    id: "moyen-ours-bonhomme",
    tier: "moyen",
    rarity: "commun",
    name: "Brounet",
    tagline: "Adore le miel, mais accepte les légumes.",
    palette: { primary: "#7A5233", secondary: "#4A3020", accent: "#D9B48F", eye: "#2B2B2B" },
    parts: { body: "blob", ears: "round", eyes: "sleepy", mouth: "smile", tail: "stub", markings: "belly_patch", extra: null },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "bell",
  },
  {
    id: "moyen-cerf-fier",
    tier: "moyen",
    rarity: "rare",
    name: "Cervin",
    tagline: "Marche des heures sans jamais se fatiguer.",
    palette: { primary: "#B98A5A", secondary: "#6F4E2A", accent: "#F7E7CE", eye: "#2B2B2B" },
    parts: { body: "tall", ears: "antlers", eyes: "big", mouth: "small", tail: "stub", markings: "spots", extra: null },
    anchors: DEFAULT_ANCHORS.tall,
    signature: "flower",
  },
  {
    id: "moyen-loup-veilleur",
    tier: "moyen",
    rarity: "rare",
    name: "Lunar",
    tagline: "Hurle à la lune quand le dîner est bon.",
    palette: { primary: "#6F7784", secondary: "#C9CFD9", accent: "#F2EFE6", eye: "#2B2B2B" },
    parts: { body: "tall", ears: "fox", eyes: "sharp", mouth: "fangs", tail: "fluffy", markings: "mask", extra: null },
    anchors: DEFAULT_ANCHORS.tall,
    signature: "bandana",
  },
  {
    id: "moyen-grenouille-ronde",
    tier: "moyen",
    rarity: "rare",
    name: "Croabelle",
    tagline: "Fait des bonds de joie après chaque repas.",
    palette: { primary: "#7FB77E", secondary: "#4F7A4E", accent: "#F0D68F", eye: "#2B2B2B" },
    parts: { body: "blob", ears: "none", eyes: "big", mouth: "smile", tail: "none", markings: "spots", extra: null },
    anchors: DEFAULT_ANCHORS.blob,
    signature: "flower",
  },
  {
    id: "moyen-lynx-brume",
    tier: "moyen",
    rarity: "tres_rare",
    name: "Brumalys",
    tagline: "Se fond dans la brume et réapparaît à l'heure du goûter.",
    palette: { primary: "#D9D5C8", secondary: "#6F776C", accent: "#7DA7D9", eye: "#4A6FA5" },
    parts: { body: "round", ears: "fox", eyes: "sharp", mouth: "small", tail: "stub", markings: "stripes", extra: "aura" },
    anchors: DEFAULT_ANCHORS.round,
    signature: "star_pin",
  },
  {
    id: "moyen-esprit-foret",
    tier: "moyen",
    rarity: "legendaire",
    name: "Sylvestre",
    tagline: "Le gardien de la forêt ne se montre qu'aux cœurs sincères.",
    palette: { primary: "#5FA88F", secondary: "#2F5E4E", accent: "#F0D68F", eye: "#F7F4EC" },
    parts: { body: "tall", ears: "antlers", eyes: "sparkle", mouth: "smile", tail: "thin", markings: "crescent", extra: ["aura", "crystals"] },
    anchors: DEFAULT_ANCHORS.tall,
    signature: "crown",
  },
];
