/**
 * Maps the food names returned by the analyzer (free French text) to one of
 * a small set of drawable kinds, for the feeding animation (spec § 4.6).
 */
/** 100 common foods + the "plate" fallback. */
export const FOOD_KINDS = [
  "salad",
  "vegetables",
  "apple",
  "pear",
  "banana",
  "orange",
  "strawberry",
  "grapes",
  "cherry",
  "peach",
  "watermelon",
  "melon",
  "lemon",
  "kiwi",
  "mango",
  "pineapple",
  "avocado",
  "berries",
  "nuts",
  "fruit",
  "tomato",
  "carrot",
  "broccoli",
  "potato",
  "corn",
  "pepper",
  "mushroom",
  "onion",
  "cucumber",
  "eggplant",
  "peas",
  "beans",
  "pumpkin",
  "olive",
  "chili",
  "garlic",
  "bread",
  "croissant",
  "toast",
  "pasta",
  "noodles",
  "lasagna",
  "rice",
  "couscous",
  "porridge",
  "cereal",
  "pancakes",
  "waffle",
  "crepe",
  "pizza",
  "burger",
  "fries",
  "sandwich",
  "hotdog",
  "taco",
  "burrito",
  "kebab",
  "sushi",
  "dumpling",
  "quiche",
  "curry",
  "soup",
  "meat",
  "sausage",
  "bacon",
  "ham",
  "meatball",
  "chicken",
  "drumstick",
  "fish",
  "shrimp",
  "egg",
  "tofu",
  "cheese",
  "yogurt",
  "milk",
  "butter",
  "cake",
  "pie",
  "donut",
  "muffin",
  "cookie",
  "chocolate",
  "candy",
  "icecream",
  "popcorn",
  "chips",
  "pretzel",
  "honey",
  "jam",
  "sauce",
  "soda",
  "juice",
  "water",
  "coffee",
  "tea",
  "beer",
  "wine",
  "smoothie",
  "milkshake",
  "plate",
] as const;
export type FoodKind = (typeof FOOD_KINDS)[number];

const normalise = (value: string) =>
  value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\u0153/g, "oe")
    .replace(/\u00e6/g, "ae");

/** Ordered: the first matching rule wins, so specific words come before generic ones. */
const RULES: ReadonlyArray<[FoodKind, RegExp]> = [
  // Dishes and prepared food (before their ingredients).
  ["fries", /\bfrites?\b|potatoes?\s*frites|french fries/],
  ["chips", /\bchips\b|nachos/],
  ["burger", /burger|hamburger|cheeseburger/],
  ["pizza", /pizza|calzone/],
  ["hotdog", /hot[- ]?dog/],
  ["taco", /tacos?\b|fajita|quesadilla/],
  ["burrito", /burrito|\bwraps?\b|enchilada/],
  ["kebab", /kebab|doner|shawarma|gyros|brochette|skewer|yakitori/],
  ["sushi", /sushi|maki|nigiri|sashimi|poke/],
  ["dumpling", /ravioli|gyoza|dumpling|dim ?sum|\bbao\b|momo|pierogi|wonton/],
  ["quiche", /quiche|tarte salee|flamiche|tourte|feuillete|friand/],
  ["curry", /curry|dahl|\bdal\b|tikka|masala|korma|chili con carne/],
  ["lasagna", /lasagne|lasagna|moussaka|parmentier|gratin/],
  ["noodles", /nouilles?|ramen|\bpho\b|udon|soba|noodles?|pad thai|bo bun|chow mein|vermicelle/],
  ["couscous", /couscous|tajine|tagine|semoule|boulgour|bulgur|taboule/],
  ["sandwich", /sandwich|panini|croque|bagel|tartine|\bclub\b|jambon-beurre/],
  ["soup", /soupe|veloute|potage|bouillon|minestrone|gaspacho|ragout|blanquette|bourguignon|pot-au-feu|cassoulet|choucroute|mijote|stew/],
  // Bakery and breakfast.
  ["croissant", /croissant|pain au chocolat|chocolatine|brioche|viennoiserie|pain aux raisins/],
  ["pancakes", /pancakes?|blini/],
  ["crepe", /crepes?\b|galette (bretonne|de sarrasin|complete)/],
  ["waffle", /gaufre|waffle/],
  ["toast", /toast|biscotte|pain grille|crouton/],
  ["porridge", /porridge|flocons? d'avoine|avoine|oatmeal|bouillie/],
  ["cereal", /cereales?|muesli|granola|corn ?flakes|barre de cereales/],
  ["bread", /\bpain\b|baguette|naan|pita|tortilla|focaccia|ciabatta|\bbun\b|pain de mie|polenta/],
  ["pasta", /pates?\b|spaghetti|penne|tagliatelle|gnocchi|macaroni|fusilli|linguine|tortellini|cannelloni|farfalle|orzo|carbonara|bolognaise/],
  ["rice", /\briz\b|risotto|paella|quinoa|epeautre|\borge\b|sarrasin|millet/],
  // Sweets and snacks.
  ["icecream", /glace|sorbet|ice ?cream|esquimau|cornet|sundae/],
  ["donut", /donut|doughnut|beignet|churros|chouquette/],
  ["muffin", /muffin|cupcake|madeleine|financier|cannele|scone/],
  ["pie", /\btartes?\b|tartelette|crumble|clafoutis|strudel|\bpie\b/],
  ["chocolate", /chocolat|brownie|nutella|cacao|fondant/],
  ["candy", /bonbon|sucette|confiserie|guimauve|reglisse|caramel|candy|sweets?\b|chewing|dragee|nougat|pate de fruit/],
  ["cookie", /cookie|biscuit|sable|galette|speculoos|petit[- ]beurre|gaufrette|shortbread|macaron|meringue/],
  ["popcorn", /pop[- ]?corn|mais souffle/],
  ["pretzel", /bretzel|pretzel|crackers?|\btuc\b|aperitif/],
  ["honey", /miel|sirop d'erable|honey/],
  ["jam", /confiture|marmelade|gelee|\bjam\b|compote/],
  ["cake", /gateau|cake|patisserie|mousse|tiramisu|flan|eclair|dessert|cheesecake|profiterole|paris-brest|mille-feuille|baba|creme brulee|panna cotta|riz au lait|pudding/],
  ["sauce", /sauce|ketchup|mayonnaise|\bmayo\b|vinaigrette|moutarde|pesto|houmous|hummus|guacamole|tzatziki|tapenade|aioli|\bdip\b/],
  // Drinks.
  ["milkshake", /milk-?shake|frappe|frappuccino/],
  ["smoothie", /smoothie|lassi/],
  ["beer", /biere|beer|cidre|panache/],
  ["wine", /\bvin\b|champagne|prosecco|cocktail|sangria|\bkir\b|mojito|spritz|whisky|vodka|rhum|\bgin\b/],
  ["juice", /\bjus\b|nectar|orangeade|citronnade/],
  ["soda", /soda|cola|coca|limonade|boisson gazeuse|energy|ice ?tea|the glace/],
  ["milk", /\blait\b|\bmilk\b|boisson vegetale/],
  ["tea", /\bthe\b|infusion|tisane|matcha|\bchai\b|rooibos|verveine/],
  ["coffee", /cafe|espresso|cappuccino|latte|expresso|chocolat chaud|moka|americano/],
  ["water", /\beau\b|water|perrier|pellegrino/],
  // Dairy.
  ["butter", /beurre|butter|margarine/],
  ["yogurt", /yaourt|yogourt|fromage blanc|skyr|petit[- ]suisse|creme dessert|kefir/],
  ["cheese", /fromage|cheddar|comte|camembert|emmental|mozzarella|parmesan|feta|chevre|\bbrie\b|raclette|fondue|gruyere|roquefort|burrata|ricotta|mascarpone|gouda|\bbleu\b|reblochon|halloumi/],
  // Proteins.
  ["tofu", /tofu|tempeh|seitan|steak vegetal|galette vegetale|proteines? de soja/],
  ["shrimp", /crevette|gambas|langoustine|homard|crabe|ecrevisse|scampi|prawn|shrimp/],
  ["egg", /\boeufs?\b|omelette|\beggs?\b/],
  ["drumstick", /cuisse|pilon|aile de poulet|\bwings?\b|drumstick|poulet roti|poulet frit|nuggets?/],
  ["chicken", /poulet|volaille|dinde|canard|chicken|cordon bleu|pintade|caille|escalope|magret|turkey/],
  ["fish", /poisson|saumon|thon|cabillaud|truite|sardine|maquereau|moule|huitre|calamar|fruits? de mer|dorade|\bbar\b|colin|\blieu\b|hareng|anchois|surimi|\bsole\b|merlu|lotte|saint-jacques|coquille|\bfish\b|tilapia|espadon|encornet|poulpe|seiche/],
  ["sausage", /saucisse|saucisson|merguez|chorizo|knack|andouille|boudin|salami|wurst|francfort/],
  ["bacon", /bacon|lardons?|poitrine fumee|pancetta|guanciale/],
  ["ham", /jambon|prosciutto|coppa|bresaola|charcuterie|rillette|\bpate\b|terrine|mortadelle/],
  ["meatball", /boulette|kefta|kofta|meatball|polpette/],
  ["meat", /viande|boeuf|steak|porc|agneau|mouton|veau|cotelette|entrecote|\broti\b|hache|lapin|foie|gigot|filet mignon|bavette|carpaccio|tartare|bifteck|cote de|travers|\bribs\b|pulled pork|gibier|cerf|sanglier|biche|onglet|rumsteck|faux-filet|tournedos|paleron/],
  // Vegetables (before generic fruit / vegetables).
  ["potato", /pomme de terre|pommes de terre|patates?(?! douce)|puree|hash ?brown|rosti|potato/],
  ["tomato", /tomate|tomato/],
  ["carrot", /carotte|carrot/],
  ["broccoli", /brocoli|chou-fleur|chou fleur|romanesco|broccoli|cauliflower/],
  ["corn", /\bmais\b|\bcorn\b|\bepi\b/],
  ["pepper", /poivron|bell pepper/],
  ["mushroom", /champignon|cepe|girolle|shiitake|pleurote|morille|mushroom/],
  ["onion", /oignon|poireau|echalote|ciboule|onion|leek/],
  ["cucumber", /concombre|cornichon|cucumber|pickle/],
  ["eggplant", /aubergine|eggplant/],
  ["peas", /petits? pois|haricots? verts?|edamame|pois gourmands?|mange-tout|green beans?/],
  ["beans", /lentilles?|pois chiches?|haricots? (rouge|blanc|noir|sec|coco|tarbais)|feves?|flageolets?|legumineuse|beans?\b|azuki/],
  ["pumpkin", /potiron|courges?\b|butternut|potimarron|citrouille|patate douce|pumpkin|squash/],
  ["olive", /olives?\b/],
  ["chili", /piment|jalapeno|harissa|sriracha|tabasco|paprika|chipotle/],
  ["garlic", /\bail\b|garlic|gousse/],
  // Fruits.
  ["avocado", /avocat|avocado/],
  ["banana", /banane|banana|plantain/],
  ["orange", /orange|clementine|mandarine|pamplemousse|tangerine|kumquat|agrume/],
  ["lemon", /citron|\blime\b|lemon|yuzu|bergamote/],
  ["strawberry", /fraise|strawberr/],
  ["berries", /myrtille|framboise|\bmures?\b|cassis|groseille|cranberr|airelle|blueberr|raspberr|fruits? rouges?|\bbaies?\b|goji|sureau/],
  ["grapes", /raisin|grape/],
  ["cherry", /cerise|griotte|cherr/],
  ["pear", /poire|\bpear\b|coing/],
  ["apple", /\bpommes?\b|apple/],
  ["peach", /peche|abricot|nectarine|brugnon|prune|mirabelle|quetsche|peach|apricot|plum/],
  ["watermelon", /pasteque|watermelon/],
  ["melon", /melon|cantaloup|honeydew/],
  ["kiwi", /kiwi/],
  ["mango", /mangue|mango|papaye|papaya|goyave|fruit de la passion|litchi|lychee|grenade|pomegranate|figue|\bfigs?\b|dattes?|kaki|carambole/],
  ["pineapple", /ananas|pineapple|noix de coco|\bcoco\b/],
  ["nuts", /\bnoix\b|amande|noisette|cacahuete|pistache|cajou|pecan|pignon|graines?|sesame|\bchia\b|\blin\b|tournesol|almond|peanut|walnut|hazelnut|cashew/],
  ["fruit", /fruit/],
  // Generic greens and vegetables last.
  ["salad", /salade|laitue|roquette|mache|mesclun|crudites?|coleslaw|epinards?|kale|cresson|endive|\bchoux?\b|betterave|radis|fenouil|celeri|artichaut|asperge|verdure|greens?\b|lettuce|spinach/],
  ["vegetables", /legume|courgette|navet|ratatouille|\bwok\b|poelee|persil|herbes?|basilic|coriandre|menthe|jardiniere|macedoine|zucchini|vegetable|veggie|topinambour|panais|blette|bette|rutabaga|salsifis|germes?|pousses?|algue|nori|wakame/],
];

/** Kind of drawing for one food name; `plate` when nothing matches. */
export function classifyFood(name: string): FoodKind {
  const n = normalise(name);
  for (const [kind, rule] of RULES) if (rule.test(n)) return kind;
  return "plate";
}

/**
 * Distinct kinds to draw for a meal, in the analyzer's order (the main
 * ingredients come first), at most `max`. An empty list gives one plate.
 */
export function foodKindsFor(foods: readonly string[], max = 3): FoodKind[] {
  const kinds: FoodKind[] = [];
  for (const food of foods) {
    const kind = classifyFood(food);
    if (!kinds.includes(kind)) kinds.push(kind);
    if (kinds.length >= max) break;
  }
  if (kinds.length === 0) kinds.push("plate");
  return kinds;
}

export const FOOD_KIND_LABELS: Record<FoodKind, string> = {
  salad: "salade",
  vegetables: "légumes",
  apple: "pomme",
  pear: "poire",
  banana: "banane",
  orange: "orange",
  strawberry: "fraise",
  grapes: "raisin",
  cherry: "cerises",
  peach: "pêche",
  watermelon: "pastèque",
  melon: "melon",
  lemon: "citron",
  kiwi: "kiwi",
  mango: "mangue",
  pineapple: "ananas",
  avocado: "avocat",
  berries: "fruits rouges",
  nuts: "noix et graines",
  fruit: "fruits",
  tomato: "tomate",
  carrot: "carotte",
  broccoli: "brocoli",
  potato: "pomme de terre",
  corn: "maïs",
  pepper: "poivron",
  mushroom: "champignon",
  onion: "oignon",
  cucumber: "concombre",
  eggplant: "aubergine",
  peas: "petits pois",
  beans: "légumineuses",
  pumpkin: "courge",
  olive: "olives",
  chili: "piment",
  garlic: "ail",
  bread: "pain",
  croissant: "croissant",
  toast: "toast",
  pasta: "pâtes",
  noodles: "nouilles",
  lasagna: "lasagnes",
  rice: "riz",
  couscous: "couscous",
  porridge: "porridge",
  cereal: "céréales",
  pancakes: "pancakes",
  waffle: "gaufre",
  crepe: "crêpe",
  pizza: "pizza",
  burger: "burger",
  fries: "frites",
  sandwich: "sandwich",
  hotdog: "hot-dog",
  taco: "taco",
  burrito: "burrito",
  kebab: "brochette",
  sushi: "sushi",
  dumpling: "raviolis",
  quiche: "quiche",
  curry: "curry",
  soup: "plat mijoté",
  meat: "viande",
  sausage: "saucisse",
  bacon: "bacon",
  ham: "jambon",
  meatball: "boulettes",
  chicken: "volaille",
  drumstick: "pilon de poulet",
  fish: "poisson",
  shrimp: "crevette",
  egg: "œuf",
  tofu: "tofu",
  cheese: "fromage",
  yogurt: "yaourt",
  milk: "lait",
  butter: "beurre",
  cake: "gâteau",
  pie: "tarte",
  donut: "donut",
  muffin: "muffin",
  cookie: "biscuit",
  chocolate: "chocolat",
  candy: "bonbon",
  icecream: "glace",
  popcorn: "pop-corn",
  chips: "chips",
  pretzel: "bretzel",
  honey: "miel",
  jam: "confiture",
  sauce: "sauce",
  soda: "soda",
  juice: "jus de fruits",
  water: "eau",
  coffee: "café",
  tea: "thé",
  beer: "bière",
  wine: "vin",
  smoothie: "smoothie",
  milkshake: "milkshake",
  plate: "assiette",
};
